package com.syfttny.watchmytank.domain.model

import java.time.LocalDateTime
import java.time.temporal.ChronoUnit

/**
 * Represents a user-defined reminder for aquarium tasks.
 *
 * @property id Unique identifier, typically auto-generated by the database.
 * @property name User-defined name for the reminder (e.g., "Feed Guppies", "Water Change").
 * @property type The frequency type of the reminder.
 * @property frequencyDays The number of days for the EVERY_N_DAYS type. Null otherwise.
 * @property cronExpression The cron expression string for the CRON type. Null otherwise.
 * @property creationTime Timestamp when the reminder was initially created.
 * @property nextTriggerTime Timestamp for the next scheduled notification.
 * @property triggerHour Hour of the day (0-23)
 * @property triggerMinute Minute of the hour (0-59)
 * @property isEnabled Whether the reminder is currently active.
 * @property lastTriggeredTime Timestamp when the reminder last successfully triggered a notification.
 */
data class Reminder(
    val id: Long = 0,
    val name: String,
    val type: ReminderType,
    val frequencyDays: Int? = null,
    val cronExpression: String? = null,
    val creationTime: LocalDateTime,
    var nextTriggerTime: LocalDateTime,
    val triggerHour: Int? = null,
    val triggerMinute: Int? = null,
    val isEnabled: Boolean = true,
    var lastTriggeredTime: LocalDateTime? = null
) {
    /**
     * Calculates the next trigger time based on the current trigger time and reminder type.
     * Returns null if the type is unsupported or data is invalid (e.g., null frequencyDays for EVERY_N_DAYS).
     */
    fun calculateNextTriggerTime(currentTriggerTime: LocalDateTime = this.nextTriggerTime): LocalDateTime? {
        return when (type) {
            ReminderType.DAILY -> {
                // Add one day to the current trigger time
                currentTriggerTime.plusDays(1)
            }
            ReminderType.EVERY_N_DAYS -> {
                // Add 'frequencyDays' to the current trigger time
                frequencyDays?.let { days ->
                    if (days > 0) {
                        currentTriggerTime.plusDays(days.toLong())
                    } else {
                        null // Invalid frequency
                    }
                } ?: null // frequencyDays should not be null for this type
            }
            ReminderType.CRON -> {
                // TODO: Implement CRON parsing logic.
                // This likely requires a third-party CRON library.
                // For now, return null or handle as an error/unsupported.
                // Example: Use a library like 'com.cronutils:cron-utils'
                // val definition = CronDefinitionBuilder.instanceDefinitionFor(CronType.UNIX)
                // val parser = CronParser(definition)
                // val executionTime = ExecutionTime.forCron(parser.parse(cronExpression))
                // val nextExecution = executionTime.nextExecution(ZonedDateTime.of(currentTriggerTime, ZoneId.systemDefault()))
                // nextExecution.map { it.toLocalDateTime() }.orElse(null)
                null // Placeholder
            }
        }
    }
}

/**
 * Defines the possible frequency types for a reminder.
 */
enum class ReminderType {
    /** Reminder triggers every day at a specific time (handled by scheduling logic). */
    DAILY,
    /** Reminder triggers every N days. */
    EVERY_N_DAYS,
    /** Reminder triggers based on a specific CRON expression for complex schedules. */
    CRON
} 