package com.syfttny.watchmytank.domain.model

import java.time.LocalDateTime
import java.time.temporal.ChronoUnit
import com.syfttny.watchmytank.domain.model.ReminderType

/**
 * Represents a user-defined reminder for aquarium tasks.
 *
 * @property id Unique identifier, typically auto-generated by the database.
 * @property name User-defined name for the reminder (e.g., "Feed Guppies", "Water Change").
 * @property type The frequency type of the reminder.
 * @property frequencyDays The number of days for the EVERY_N_DAYS type. Null otherwise.
 * @property cronExpression The cron expression string for the CRON type. Null otherwise.
 * @property creationTime Timestamp when the reminder was initially created.
 * @property nextTriggerTime Timestamp for the next scheduled notification.
 * @property triggerHour Hour of the day (0-23)
 * @property triggerMinute Minute of the hour (0-59)
 * @property isEnabled Whether the reminder is currently active.
 * @property lastTriggeredTime Timestamp when the reminder last successfully triggered a notification.
 */
data class Reminder(
    val id: Long = 0,
    val name: String,
    val type: ReminderType,
    val frequencyDays: Int? = null,
    val cronExpression: String? = null,
    val creationTime: LocalDateTime,
    var nextTriggerTime: LocalDateTime,
    val triggerHour: Int? = null,
    val triggerMinute: Int? = null,
    val isEnabled: Boolean = true,
    var lastTriggeredTime: LocalDateTime? = null
) {
    fun calculateNextTriggerTime(currentTriggerTime: LocalDateTime = this.nextTriggerTime): LocalDateTime? {
        return when (type) {
            ReminderType.DAILY -> {
                
                currentTriggerTime.plusDays(1)
            }
            ReminderType.EVERY_N_DAYS -> {
                
                frequencyDays?.let { days ->
                    if (days > 0) {
                        currentTriggerTime.plusDays(days.toLong())
                    } else {
                        null 
                    }
                } ?: null 
            }
            ReminderType.CRON -> {
                null // Placeholder
            }
        }
    }
}

enum class ReminderType {
    DAILY,
    EVERY_N_DAYS,
    CRON
} 