package com.syfttny.watchmytank.domain.model

import java.time.LocalDateTime

data class WaterParameterLog(
    val id: Long = 0, // Local database primary key (auto-generated by Room)
    val timestamp: LocalDateTime = LocalDateTime.now(),
    val parameterType: ParameterType, // Enum to define the type
    val value: Double, // The measured value
    val notes: String? = null,
    // TODO: Add userId if implementing multi-user support later
    // val userId: String? = null
)