package com.syfttny.watchmytank.data.mapper

import com.google.gson.Gson
import com.google.gson.reflect.TypeToken
import com.syfttny.watchmytank.data.local.entity.ParameterLogEntity
import com.syfttny.watchmytank.domain.model.ParameterLog
import com.syfttny.watchmytank.domain.model.ParameterType

// Reusable Gson instance
private val gson = Gson()
private val mapTypeToken = object : TypeToken<Map<ParameterType, Double>>() {}.type

/**
 * Converts a [ParameterLog] (domain model) to a [ParameterLogEntity] (Room entity).
 */
fun ParameterLog.toEntity(): ParameterLogEntity {
    // Convert the parameters map to JSON String
    val parametersJsonString = gson.toJson(this.parameters, mapTypeToken)
    return ParameterLogEntity(
        // id is auto-generated by Room, so we don't set it here
        // If updating an existing entity, we'd need to handle the id.
        tankId = this.tankId,
        userId = this.userId,
        timestamp = this.timestamp,
        parametersJson = parametersJsonString,
        notes = this.notes,
        isSynced = false // Assume new logs are not synced by default
    )
}

/**
 * Converts a [ParameterLogEntity] (Room entity) to a [ParameterLog] (domain model).
 */
fun ParameterLogEntity.toDomainModel(): ParameterLog {
    // Convert the JSON String back to the parameters map
    val parametersMap: Map<ParameterType, Double> = try {
        gson.fromJson(this.parametersJson, mapTypeToken)
            ?: emptyMap() // Handle null or invalid JSON
    } catch (e: Exception) {
        // Log error or handle appropriately if JSON is corrupt
        println("Error parsing parametersJson for entity id ${this.id}: ${e.message}")
        emptyMap()
    }
    return ParameterLog(
        id = this.id.toString(), // Convert Long ID to String for domain model if needed
        tankId = this.tankId,
        userId = this.userId,
        timestamp = this.timestamp,
        parameters = parametersMap,
        notes = this.notes
        // isSynced status is typically handled within the repository/data layer,
        // so it might not be needed in the domain model itself.
    )
} 